### ISSUE TITLE
Why not stick with the initial record base structure?

### ISSUE THREAD

**Issue by RogerMostad** [zambal/queue#1]
Hi, nice work.

I am not sure how many of the other OTP libraries use the Queue type.  If they do this version won't inter-operate with those libraries.

I don't think a record implementation would be any slower and would actually have a slightly smaller memory footprint.

I guess since I mentioned it I should be prepared to do it;-) It would be a good exercise.

**Comment by zambal** [comment]
Hi,

The reason for using a struct is that it enables us to implement useful protocols like Enumerable, Collectable and Inspect. This wouldn't be possible when using Erlang's queue data format, which btw is a 2 element tuple and not a record.

As far as I know no OTP libraries use the queue module in their public API, so I don't think there will be any interoperability problems. Furthermore, it would be trivial to implement a `to_erl` function that coverts the Queue struct to Erlangs queue tuple format.

You are right that queue's tuple format has a slightly smaller memory footprint and it probably is a little bit faster too, but I suspect the difference is minimal and the benefits of being able to use protocols outweigh the tiny performance degradation.

**Comment by zambal** [comment]
I've included `to_erl/1` and `from_erl/1` functions that convert to and from :queue's data type in 8fcd671cd3bed5a37b0295da79de0c53467617e1

**Comment by RogerMostad** [comment]
Hi Vincint,

Thanks for the reply.  I was going to update you with my wonderful changes I had made until I face planted into the protocol issue;-)  I guess adding a from_erlang_queue and to_erlang_queue could be added for compatibility but I like that Collectable, Inspect and Enumerable are available as protocols.  They are probably much more useful than just having backwards compatibility.

It is unfortunate that you can't have the protocols on tuple based structures as there are some neat ones in OTP.

Regards,

Roger Mostad

**\* Please make note of our new address below. ***

......................................................

Enablecore Technologies Inc.

215-2383 King George Blvd

Surrey BC  V4A 5A4

T: 1-604-270-1020

F: 1-604-270-1029

.......................................................

---

Return-Path: <bounces+848413-e20c-rmostad=enablecore.com@sgmail.github.com>
Received: from o6.sgmail.github.com [192.254.113.101] by mail62.safesecureweb.com with SMTP;
   Tue, 13 Oct 2015 08:29:51 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
    h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
    s=s20150108; bh=06xwMSck0tGsQcpGS0soAkWQMIc=; b=aK8drBAaWoUWkCJ3
    oLEOwu3EpE2z8eidIHFXXN8CAhDmP6yycujSRdbtxZmft5xb7DnjqJ0koEF4pS+4
    GN84GHvpZNVNFVXzAZJ9nDFWHK8UTd6gdNWmFn78ITHaixWuq2AMrNtPeXknuDTH
    BTjJJqMmHKdlQiwjrjFqd/XY3zg=
Received: by filter0439p1mdw1.sendgrid.net with SMTP id filter0439p1mdw1.12687.561CF93429
        2015-10-13 12:29:40.292256683 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
    by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id h2v2FNsoSl-tWaoSYtddGA
    for rmostad@enablecore.com; Tue, 13 Oct 2015 12:29:40.274 +0000 (UTC)
Date: Tue, 13 Oct 2015 05:29:40 -0700

**Comment by RogerMostad** [comment]
Thanks again.

Better function defs than I suggested.  You could have sent this email before I wrote that long winded reply!

Regards,

Roger Mostad

**\* Please make note of our new address below. ***

......................................................

Enablecore Technologies Inc.

215-2383 King George Blvd

Surrey BC  V4A 5A4

T: 1-604-270-1020

F: 1-604-270-1029

.......................................................

---

Return-Path: noreply@github.com
Received: from github-smtp2-ext2.iad.github.net [192.30.252.193] by mail62.safesecureweb.com with SMTP;
   Tue, 13 Oct 2015 14:56:04 -0400
Date: Tue, 13 Oct 2015 11:56:04 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
    s=pf2014; t=1444762564;
    bh=VZ8KKd4QeWnhbTlxuFf1BCvITwK+iFhXd9ILk8ciJMI=;
    h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
     List-Archive:List-Post:List-Unsubscribe:From;
    b=ZL495WR0RtJOFdmbgSi20VdkOOmnTpnHSiblrjAiyTBl/Apfkhady2c9aFFysHrnx
     TOQnWz7rN5JKgs1FjCGYfbuVI0IKmhwbqinNnvlV/pZTDfuojLWhovjEsIaeJKRq99
     kxdLsaL0YLkTcWxDfSYiC5zUyHwOg5qfBYWpaNn4=

**Comment by zambal** [comment]
I think our replies just crossed each other :)
